#!/bin/bash
git add .
	read -p "Introduce el mensaje del commit: " commit_message
	if [ -z "$commit_message" ]; then
        commit_message="commit message"
        echo "Mensaje de commit vacío. Usando mensaje predeterminado: '$commit_message'"
	fi
	git commit -m "$commit_message"
	git push origin brahian

